### ISSUE TITLE
Set-up Kanban board

### ISSUE THREAD

**Issue by UbdaNam** [UbdaNam/TV-Show#21]
Link to our GitHub Repository: https://github.com/UbdaNam/Meals/projects/1

**Note**: We are a group of 2 students

**Comment by emmiiorji** [comment]
Hi @UbdaNam and @hasnatali1947, 

# Status: Approved ✅

Your project Kanban board is all set up!  There is nothing else to say other than... it's time to start implementing your project :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220871050-9893fe6a-46a0-42a3-8a44-46ac0f7f1154.gif'/>
</div>

## Good Highlights✔️

- Project tasks has been evenly distributed between team members


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by UbdaNam** [comment]
Thank you for reviewing out kanban board 😀
